<?
    /**
     * STEPS TO FOLLOW ON THIS FILE:
     * 1. fill all of the required data below
     * 2. change $db['on'] to true
     * 3. rename this file to _db_vars.inc
     * 4. ?????????????
     * 5. PROFIT!
     */

    $db = Array();
    $db['on'] = false;

    if($db['on']) {
        $db['host'] = "";
        $db['name'] = "";
        $db['user'] = "";
        $db['pass'] = "";

        $db['fb_in_db'] = false; // are fb settings stored in db 
    }

?>
